// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_f_7Mx0a3wVq4kN-qOHL2PK-ms4_zeb0',
    appId: '1:87514081140:web:a182298b056f32f2f26e21',
    messagingSenderId: '87514081140',
    projectId: 'connectapp-ec74a',
    authDomain: 'connectapp-ec74a.firebaseapp.com',
    storageBucket: 'connectapp-ec74a.appspot.com',
    measurementId: 'G-D1DQPW0XL2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFP6EONAJqcNZakW5W4EOi191I4AkOmX8',
    appId: '1:87514081140:android:53eb7f7c2b3e0587f26e21',
    messagingSenderId: '87514081140',
    projectId: 'connectapp-ec74a',
    storageBucket: 'connectapp-ec74a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9H_q_eEb4r23ypc6ZxWUOVALXk9ke0M',
    appId: '1:87514081140:ios:f4f5a0b24e73ed1ff26e21',
    messagingSenderId: '87514081140',
    projectId: 'connectapp-ec74a',
    storageBucket: 'connectapp-ec74a.appspot.com',
    iosBundleId: 'com.example.testFlutterfire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ9H_q_eEb4r23ypc6ZxWUOVALXk9ke0M',
    appId: '1:87514081140:ios:097f455ff3fb98eaf26e21',
    messagingSenderId: '87514081140',
    projectId: 'connectapp-ec74a',
    storageBucket: 'connectapp-ec74a.appspot.com',
    iosBundleId: 'com.example.testFlutterfire.RunnerTests',
  );
}
